[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "map-converter"
version = "0.1.0"
description = ""
authors = []
packages = [
    { include = "convert_map.py" },
    { include = "crdesigner" },
]

[tool.poetry.dependencies]
python = "^3.10"
torchdrivesim = ">=0.2.2"
lanelet2 = "*"
commonroad-io = "*"
lxml = "*"
pyproj = "*"
mgrs = "*"
