[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "map-converter"
version = "0.1.0"
dependencies = [
    "torchdrivesim>=0.2.2",
    "lanelet2",
    "commonroad-io",
    "lxml",
    "pyproj",
    "mgrs",
]

[tool.setuptools]
py-modules = ["convert_map"]

[tool.setuptools.packages.find]
where = ["."]
